# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-04 09:53
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_number', models.IntegerField(blank=True, null=True)),
                ('sector', models.CharField(blank=True, max_length=65)),
                ('preference', models.CharField(blank=True, choices=[('single', 'eenmalig opdracht'), ('long', 'langdurige opdracht')], max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Bedrijfsdetails',
            },
        ),
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(blank=True, max_length=65)),
                ('education', models.CharField(blank=True, max_length=65)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Studentendetails',
            },
        ),
        migrations.CreateModel(
            name='UserFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=65)),
                ('thema', models.CharField(blank=True, max_length=65)),
                ('word_count', models.IntegerField(blank=True)),
                ('upload_date', models.DateTimeField()),
                ('accept_date', models.DateTimeField(blank=True)),
                ('end_date', models.DateTimeField()),
                ('price', models.FloatField(blank=True)),
                ('checker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_checker', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_texter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(blank=True, choices=[('man', 'Man'), ('vrouw', 'Vrouw'), ('andere', 'Anders')], max_length=10)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('hook_up', models.CharField(blank=True, choices=[('Social media', (('facebook', 'Facebook'), ('twitter', 'Twitter'), ('linked', 'LinkedIn'), ('andere', 'Andere'))), ('evenement', 'Evenement'), ('andere', 'Andere')], max_length=10, null=True)),
                ('payment', models.CharField(blank=True, choices=[('paypal', 'Paypal'), ('bank', 'Bankkaart'), ('bitcoint', 'Bitcoint')], max_length=10, null=True)),
                ('status', models.CharField(choices=[('student', 'Student'), ('bedrijf', 'Bedrijf'), ('algemene gebruiker', 'Algemeen gebruiker')], max_length=100)),
                ('company_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.CompanyDetails')),
                ('student_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.StudentDetails')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z_ ]*$', 'Enkel letters toegelaten bv a-z,A-Z')])),
            ],
            options={
                'verbose_name_plural': 'gebruikerstypen',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.UserType'),
        ),
    ]
