# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-22 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='improved_file',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
