# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-07 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='end_date',
            field=models.DateTimeField(default=None),
        ),
    ]
