# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-22 13:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_userfile_improved_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField()),
                ('user_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.UserFile')),
            ],
        ),
    ]
