# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-07 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20170607_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='end_date',
            field=models.DateTimeField(),
        ),
    ]
