# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-07 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20170607_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to=b''),
            preserve_default=False,
        ),
    ]
