# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-22 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20170622_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='user_file',
        ),
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.UserProfile'),
        ),
    ]
